name: 'Blank Issue Form'
description: 'Standard template for HackforLA. Tips for writing a good issue are included inside.'

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less. This should be in the form of a user story and why we are doing this. We need to do x for y reason.
    validations:
      required: true
 - type: textarea
    id: background
    attributes:
      label: Background
      description: " OPTIONAL: When documenting your work for future reference, TELL A STORY of your work's purpose and context. Make your summary detailed enough that someone unfamiliar to your work would be able to follow along. Put yourself in the shoes of a hiring manager in an interview, or a newbie to the team. Link other relevant issues with # and mention relevant teammates with @."
    
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the the steps to be completed for example research or reporting. Think of this as a checklist of the smaller tasks you need to do for now. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues."
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, previous work by another Hack for LA's person or project, external sites with solutions, documentation, etc."
    validations:
      required: true
      
      - type: markdown
    attributes:
      value: "# Additional Instructions"
  
  - type: markdown
    attributes:
      value: |
        1. Add assignee(s), label(s) (how long the work will take, what skillset is required), project(s) (which Kanban board), and milestone (the greater context that this issue is part of). This issue will automatically have the ? question label applied. Remove it after you've notified the PM or the leads of your task.

        2. After submitting this issue and as you complete the tasks, make comments adding your thought process, i.e., "Teammate x and I collaborated on this task in this Figma file: http... We decided that the most important takeaways from the participant 1 session was y. Based on y, we recommend design changes a, b, and c, because... Update, we discussed a, b, and c in the all-hands meeting last week and our recommendations are set to be completed next month, and is being documented in issue #
